FROM debian:bullseye

RUN apt-get update && apt-get install -y wget gnupg && \
    wget -q -O - https://vitastor.io/debian/pubkey | apt-key add - && \
    echo 'deb https://vitastor.io/debian bullseye main' >> /etc/apt/sources.list && \
    apt-get update && apt-cache madison vitastor && apt-get install -y vitastor=2.2.2-1bullseye lp-solve && apt-get clean

ENTRYPOINT ["node", "/usr/lib/vitastor/mon/mon-main.js"]
