name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get short commit SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Build and Push Docker image with Kaniko
        uses: https://code.thetadev.de/actions/kaniko@v1
        with:
          image: gitinsky/vitastor-osd
          tag: ${{ env.SHORT_SHA }}
          tag_with_latest: true
          username: gitinsky
          password: ${{ secrets.DOCKERHUB_TOKEN }}
